apps/django_demo/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^', views.index, name='index'),
    url(r'^logOut', views.logOut, name='logOut'),
    url(r'^poke/', views.addPoke, name='pokeMe'),
]

apps/new_login/urls.py
from django.conf.urls import url
from . import views
from views import index, create_user, login, success, removeUser

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register$', create_user, name='create_user'),
    url(r'^login$', login, name='login'),
    url(r'^success$', success, name='success'),
    url(r'^selectAccount/(?P<id>[0-9]*)/delete', removeUser, name='removeUser'),
]

django_test/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.new_login.urls', namespace='users')),
    url(r'^profile/', include('apps.django_demo.urls', namespace='pokes'))
]

apps/django_demo/models.py
from __future__ import unicode_literals

from django.db import models
from ..new_login.models import User
# Create your models here.
class PokeManager(models.Manager):
    def addPoke(self, user_id):
        new_poke = self.create(user=user_id)
        return new_poke

class Pokes(models.Model):
    user = models.ForeignKey(User, related_name='userPokes')
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    pokeMgr=PokeManager()

apps/new_login/models.py
from __future__ import unicode_literals
import re, bcrypt
from django.db import models

# Create your models here.
EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

class UserManager(models.Manager):
    def createUser(self, data):
        response = {}
        errors = self.validateRegister(data)
        if len(errors) > 0:
            response['created'] = False
            response['errors'] = errors
        else:
            password = bcrypt.hashpw(data['password'].encode(), bcrypt.gensalt())
            new_user = self.create(first_name = data['fname'], last_name = data['lname'], alias = data['alias'], email = data['email'], password=password)
            response['created'] = True
            response['new_user'] = new_user
        return response

    def login(self, data):
        response = {}
        errors = self.validateLogin(data)
        #IMPORTANT: .GET works if there is one record that matches,
        # if there are 0 or more than one, .GET returns an error
        #return user with the email password
        if len(errors) > 0:
            response['loggedIn'] = False
            response['errors'] = errors
            return response
        else:
            user_login = User.objects.get(email=data['email'])
            password_hash = bcrypt.hashpw(data['password'].encode(), user_login.password.encode())
            response['loggedIn'] = True
            response['id'] = user_login.id
            response['first_name'] = user_login.first_name
            response['created'] = True
            return response

    def deleteUser(request, id):
        e = User.objects.get(id=id)
        if not e:
            return False
        else:
            e.delete()
            return True

    #helper methods to validate info
    def validateRegister(self, data):
        errors = []
        if len(data['fname']) < 2 or len(data['lname']) < 2:
            errors.append("First and Last names must be at least 2 Characters")
        if len(data['password']) < 8:
            errors.append("Password Must be at least 8 Characters")
        if not data['fname'].isalpha() or not data['lname'].isalpha():
            errors.append("First and Last name can only be letters")
        if len(data['alias']) < 2:
            errors.append("User Alias must be at least 2 Characters")
        if data['password'] != data['confirmpass']:
            errors.append('Confirm Password does not match')

        existing_email = self.filter(email = data['email'])
        if existing_email:
            errors.append('Submitted Email already exists in the Database')
        if not EMAIL_REGEX.match(data['email']):
            errors.append("Not a Valid Email, Please Try Again")
        return errors

    def validateLogin(self, data):
        errors = []

        if len(data['email']) < 2:
            errors.append("Email cannot be blank")
        if len(data['password']) < 8:
            errors.append("Password is Invalid/Doesn't Match")
        if not EMAIL_REGEX.match(data['email']):
            errors.append("Invalid Email")
        #checks for existing email, if doesn't, breaks and returns error
        existing_user = self.filter(email=data['email'])
        if not existing_user:
            errors.append("User doesn't exist, please Register")
            return errors
        return errors


class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    alias = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    password = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = UserManager()

apps/django_demo/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from .models import Pokes
from ..new_login.models import User

# Create your views here.
def index(request):
    this_user = User.objects.get(id=request.session['id'])
    all_users = User.objects.all()
    context = {
        'all_users':all_users,
        'this_user':this_user,
    }
    return render(request, 'django_demo/index.html', context)

def addPoke(request):
    print "fuck this bullshit"
    if request.method =='POST':
        target_user = User.objects.get(id=id)
        addPoke = Pokes.pokeMgr.addPoke(request.POST, target_user)
    return redirect(reverse('pokes:index'))

def logOut(request):
    request.session.clear()
    return redirect(reverse('users:index'))

apps/new_login/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, UserManager
from django.core.urlresolvers import reverse
# Create your views here.

def index(request):
    return render(request, 'new_login/index.html')

def create_user(request):
    if request.method == 'POST':
        new_user = User.objects.createUser(request.POST)

        if new_user['created']:
            messages.success(request, new_user['new_user'].email + " was Successfully Registered, You May Login Now")
            return redirect('/')
        else:
            for error in new_user['errors']:
                messages.error(request, error)
            return redirect('/')

def login(request):
    if request.method =='POST':
        login = User.objects.login(request.POST)
        if login['loggedIn']:
            messages.success(request, "Welcome " + login['first_name'] + ", Successfully Logged In ")
            request.session['id'] = login['id']
            return redirect(reverse('pokes:index'))
        else:
            for error in login['errors']:
                messages.error(request, error)
            return redirect('/')


def success(request):
    this_user = User.objects.get(id=request.session['id'])
    all_users = User.objects.all()
    context = {
        'users': all_users,
        'this_user': this_user
    }
    return render(request, 'new_login/loginsuccess.html', context)

def removeUser(request, id):
    result = User.objects.deleteUser(id)
    if result:
        return redirect('/success')
    else:
        print "User not Found"

apps/django_demo/templates/django_demo/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'django_demo/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <h2>Welcome {{ this_user.first_name }}</h2>
    <a href="{% url 'pokes:logOut' %}" class="btn btn-default">Log Out</a>
    <div class='container'>
      <h4>recent poke box</h4>
    </div>
    <div class='container'>
      <h3>People you may want to poke: </h3>
       <table class="table table-bordered table-hover">
           <thead>
               <tr>
                   <th>Name</th>
                   <th>Alias</th>
                   <th>Email Address</th>
                   <th>Poke History</th>
                   <th>Actions</th>
               </tr>
           </thead>
           {% for user in all_users %}
             <tr>
               <td>{{ user.first_name }} {{user.last_name}}</td>
               <td>{{ user.alias }}</td>
               <td>{{ user.email }}</td>
               <td> {{ user.userPokes.count }}</td>
               <td>
                   <form action="{% url 'pokes:pokeMe' %}" method='POST'>
                     {% csrf_token %}
                     <input type='hidden' value=1>
                     <input type='submit' value='Poke!'>
                   </form>
               </td>
             </tr>
           {% endfor %}
       </table>
     </div>

  </body>
</html>

apps/new_login/templates/new_login/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'new_login/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div id='loginBlock'>
      <h2>Login</h2>
      <form action='/login' method='POST'>
        {% csrf_token %}
        <label for=''>Email: <input type ='text' name='email'></label>
        <label for=''>Password: <input type='text' name='password'></label>
        <input type='submit' value='Login'>
      </form>
    </div>
    {% if messages %}
    <ul class='messages'>
        {% for message in messages%}
        <li{% if message.tags%} class="{{message.tags}}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div id='regBlock'>
      <h2>Registration</h2>
      <form action='/register' method='POST'>
        {% csrf_token %}
        <p>First Name: <input type ='text' name='fname'></p>
        <p>Last Name: <input type ='text' name='lname'></p>
        <p>Alias: <input type='text' name='alias'></p>
        <p>Email: <input type ='text' name='email'></p>
        <p>Password: <input type ='text' name='password'></p>
        <p>Confirm Password: <input type ='text' name='confirmpass'></p>
        <input type='date' name=bday>
        <input type='submit' value='Register'>
      </form>
    </div>
  </body>
</html>

apps/new_login/templates/new_login/loginsuccess.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    {% load staticfiles %}
    <link rel='stylesheet' href="{%static 'restful_route/css/bootstrap.min.css' %}" media="screen" title="bootstrap" charset="utf-8">
  </head>
  <body>
    <h2>Success! Welcome {{ this_user.first_name }}</h2>
    {% if messages %}
      <ul class='messages'>
      {% for message in messages %}
        <li{% if message.tags %} class="{{message.tags}}"{%endif%}>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
    <table>
      <thead>
         <tr>
           <th>First Name</th>
           <th>Last Name</th>
           <th>Alias: </th>
           <th>Email</th>
           <th>Password</th>
           <th>Actions</th>
         </tr>
       </thead>
        {% for i in users %}
            <tr>
              <td>{{ i.first_name }}</td>
              <td>{{ i.last_name }}</td>
              <td>{{ i.alias }}</td>
              <td>{{ i.email }}</td>
              <td>{{ i.password }}</td>
              <td><a href="/selectAccount/{{ i.id }}/delete">Remove Account</a></td>
            </tr>
        {% endfor %}
    </table>
  </body>
</html>